#pragma once
#include <linux/input-event-codes.h>

#include "KeyCodes.h"

static Fleur::EKeyCode GetKeyCodeLinuxEvdev(uint32_t key)
{
#define KEY(x) Fleur::Key::x

    switch (key)
    {
    case KEY_A:
        return KEY(A);
    case KEY_B:
        return KEY(B);
    case KEY_C:
        return KEY(C);
    case KEY_D:
        return KEY(D);
    case KEY_E:
        return KEY(E);
    case KEY_F:
        return KEY(F);
    case KEY_G:
        return KEY(G);
    case KEY_H:
        return KEY(H);
    case KEY_I:
        return KEY(I);
    case KEY_J:
        return KEY(J);
    case KEY_K:
        return KEY(K);
    case KEY_L:
        return KEY(L);
    case KEY_M:
        return KEY(M);
    case KEY_N:
        return KEY(N);
    case KEY_O:
        return KEY(O);
    case KEY_P:
        return KEY(P);
    case KEY_Q:
        return KEY(Q);
    case KEY_R:
        return KEY(R);
    case KEY_S:
        return KEY(S);
    case KEY_T:
        return KEY(T);
    case KEY_U:
        return KEY(U);
    case KEY_V:
        return KEY(V);
    case KEY_W:
        return KEY(W);
    case KEY_X:
        return KEY(X);
    case KEY_Y:
        return KEY(Y);
    case KEY_Z:
        return KEY(Z);
    case KEY_0:
        return KEY(D0);
    case KEY_1:
        return KEY(D1);
    case KEY_2:
        return KEY(D2);
    case KEY_3:
        return KEY(D3);
    case KEY_4:
        return KEY(D4);
    case KEY_5:
        return KEY(D5);
    case KEY_6:
        return KEY(D6);
    case KEY_7:
        return KEY(D7);
    case KEY_8:
        return KEY(D8);
    case KEY_9:
        return KEY(D9);
    case KEY_KP0:
        return KEY(KP0);
    case KEY_KP1:
        return KEY(KP1);
    case KEY_KP2:
        return KEY(KP2);
    case KEY_KP3:
        return KEY(KP3);
    case KEY_KP4:
        return KEY(KP4);
    case KEY_KP5:
        return KEY(KP5);
    case KEY_KP6:
        return KEY(KP6);
    case KEY_KP7:
        return KEY(KP7);
    case KEY_KP8:
        return KEY(KP8);
    case KEY_KP9:
        return KEY(KP9);
    case KEY_KPDOT:
        return KEY(KPDecimal);
    case KEY_KPPLUS:
        return KEY(KPAdd);
    case KEY_KPMINUS:
        return KEY(KPSubtract);
    case KEY_KPASTERISK:
        return KEY(KPMultiply);
    case KEY_KPSLASH:
        return KEY(KPDivide);
    case KEY_F1:
        return KEY(F1);
    case KEY_F2:
        return KEY(F2);
    case KEY_F3:
        return KEY(F3);
    case KEY_F4:
        return KEY(F4);
    case KEY_F5:
        return KEY(F5);
    case KEY_F6:
        return KEY(F6);
    case KEY_F7:
        return KEY(F7);
    case KEY_F8:
        return KEY(F8);
    case KEY_F9:
        return KEY(F9);
    case KEY_F10:
        return KEY(F10);
    case KEY_F11:
        return KEY(F11);
    case KEY_F12:
        return KEY(F12);
    case KEY_LEFTSHIFT:
        return KEY(LeftShift);
    case KEY_RIGHTSHIFT:
        return KEY(RightShift);
    case KEY_LEFTCTRL:
        return KEY(LeftControl);
    case KEY_RIGHTCTRL:
        return KEY(RightControl);
    case KEY_LEFTALT:
        return KEY(LeftAlt);
    case KEY_RIGHTALT:
        return KEY(RightAlt);
    case KEY_LEFTMETA:
        return KEY(LeftSuper);
    case KEY_RIGHTMETA:
        return KEY(RightSuper);
    case KEY_MENU:
        return KEY(Menu);
    case KEY_SPACE:
        return KEY(Space);
    case KEY_ENTER:
        return KEY(Enter);
    case KEY_BACKSPACE:
        return KEY(Backspace);
    case KEY_TAB:
        return KEY(Tab);
    case KEY_ESC:
        return KEY(Escape);
    case KEY_INSERT:
        return KEY(Insert);
    case KEY_DELETE:
        return KEY(Delete);
    case KEY_HOME:
        return KEY(Home);
    case KEY_END:
        return KEY(End);
    case KEY_PAGEUP:
        return KEY(PageUp);
    case KEY_PAGEDOWN:
        return KEY(PageDown);
    case KEY_UP:
        return KEY(Up);
    case KEY_DOWN:
        return KEY(Down);
    case KEY_LEFT:
        return KEY(Left);
    case KEY_RIGHT:
        return KEY(Right);
    case KEY_CAPSLOCK:
        return KEY(CapsLock);
    case KEY_NUMLOCK:
        return KEY(NumLock);
    case KEY_SCROLLLOCK:
        return KEY(ScrollLock);
    case KEY_SYSRQ:
        return KEY(PrintScreen);
    case KEY_PAUSE:
        return KEY(Pause);
    case KEY_COMMA:
        return KEY(Comma);
    case KEY_DOT:
        return KEY(Period);
    case KEY_SLASH:
        return KEY(Slash);
    case KEY_SEMICOLON:
        return KEY(Semicolon);
    case KEY_EQUAL:
        return KEY(Equal);
    case KEY_MINUS:
        return KEY(Minus);
    case KEY_BACKSLASH:
        return KEY(Backslash);
    case KEY_GRAVE:
        return KEY(GraveAccent);
    case KEY_LEFTBRACE:
        return KEY(LeftBracket);
    case KEY_RIGHTBRACE:
        return KEY(RightBracket);
    default:
        return KEY(Unknown);
    }
}
