#pragma once

#include <Windows.h>

#include "KeyCodes.h"

static inline uint16_t GetKeyCode(int winKey)
{
    switch (winKey)
    {
        case VK_SPACE:
            return 0;
        case VK_OEM_7:
            return 1;
        case VK_OEM_COMMA:
            return 2;
        case VK_OEM_MINUS:
            return 3;
        case VK_OEM_PERIOD:
            return 4;
        case VK_OEM_2:
            return 5;
        case 0x30:
            return 10;
        case 0x31:
            return 11;
        case 0x32:
            return 12;
        case 0x33:
            return 13;
        case 0x34:
            return 14;
        case 0x35:
            return 15;
        case 0x36:
            return 16;
        case 0x37:
            return 17;
        case 0x38:
            return 18;
        case 0x39:
            return 19;
        case VK_OEM_1:
            return 20;
        case VK_OEM_PLUS:
            return 21;
        case 0x41:
            return 30;
        case 0x42:
            return 31;
        case 0x43:
            return 32;
        case 0x44:
            return 33;
        case 0x45:
            return 34;
        case 0x46:
            return 35;
        case 0x47:
            return 36;
        case 0x48:
            return 37;
        case 0x49:
            return 38;
        case 0x4A:
            return 39;
        case 0x4B:
            return 40;
        case 0x4C:
            return 41;
        case 0x4D:
            return 42;
        case 0x4E:
            return 43;
        case 0x4F:
            return 44;
        case 0x50:
            return 45;
        case 0x51:
            return 46;
        case 0x52:
            return 47;
        case 0x53:
            return 48;
        case 0x54:
            return 49;
        case 0x55:
            return 50;
        case 0x56:
            return 51;
        case 0x57:
            return 52;
        case 0x58:
            return 53;
        case 0x59:
            return 54;
        case 0x5A:
            return 55;
        case VK_OEM_4:
            return 60;
        case VK_OEM_5:
            return 61;
        case VK_OEM_6:
            return 62;
        case VK_OEM_3:
            return 63;
        case VK_ESCAPE:
            return 80;
        case VK_RETURN:
            return 81;
        case VK_TAB:
            return 82;
        case VK_BACK:
            return 83;
        case VK_INSERT:
            return 84;
        case VK_DELETE:
            return 85;
        case VK_RIGHT:
            return 86;
        case VK_LEFT:
            return 87;
        case VK_DOWN:
            return 88;
        case VK_UP:
            return 89;
        case VK_PRIOR:
            return 90;
        case VK_NEXT:
            return 91;
        case VK_HOME:
            return 92;
        case VK_END:
            return 93;
        case VK_CAPITAL:
            return 94;
        case VK_SCROLL:
            return 95;
        case VK_NUMLOCK:
            return 96;
        case VK_SNAPSHOT:
            return 97;
        case VK_PAUSE:
            return 98;
        case VK_F1:
            return 100;
        case VK_F2:
            return 101;
        case VK_F3:
            return 102;
        case VK_F4:
            return 103;
        case VK_F5:
            return 103;
        case VK_F6:
            return 105;
        case VK_F7:
            return 106;
        case VK_F8:
            return 107;
        case VK_F9:
            return 108;
        case VK_F10:
            return 109;
        case VK_F11:
            return 110;
        case VK_F12:
            return 111;
        case VK_F13:
            return 112;
        case VK_F14:
            return 113;
        case VK_F15:
            return 114;
        case VK_F16:
            return 115;
        case VK_F17:
            return 116;
        case VK_F18:
            return 117;
        case VK_F19:
            return 118;
        case VK_F20:
            return 119;
        case VK_F21:
            return 120;
        case VK_F22:
            return 121;
        case VK_F23:
            return 122;
        case VK_F24:
            return 123;
        case VK_NUMPAD0:
            return 140;
        case VK_NUMPAD1:
            return 141;
        case VK_NUMPAD2:
            return 142;
        case VK_NUMPAD3:
            return 143;
        case VK_NUMPAD4:
            return 144;
        case VK_NUMPAD5:
            return 145;
        case VK_NUMPAD6:
            return 146;
        case VK_NUMPAD7:
            return 147;
        case VK_NUMPAD8:
            return 148;
        case VK_NUMPAD9:
            return 149;
        case VK_DECIMAL:
            return 160;
        case VK_DIVIDE:
            return 161;
        case VK_MULTIPLY:
            return 162;
        case VK_SUBTRACT:
            return 163;
        case VK_ADD:
            return 164;
        case VK_LSHIFT:
            return 180;
        case VK_LCONTROL:
            return 181;
        case VK_LMENU:
            return 182;
        case VK_LWIN:
            return 183;
        case VK_RSHIFT:
            return 184;
        case VK_RCONTROL:
            return 185;
        case VK_RMENU:
            return 186;
        case VK_RWIN:
            return 187;
        case VK_MENU:
            return 188;
    }
