# Assimp Configuration

# Disable unnecessary features
SET(ASSIMP_BUILD_TESTS OFF)
SET(ASSIMP_BUILD_SAMPLES OFF)
SET(ASSIMP_BUILD_DOCS OFF)
SET(ASSIMP_BUILD_ASSIMP_TOOLS OFF)
SET(ASSIMP_INSTALL OFF)
SET(ASSIMP_INJECT_DEBUG_POSTFIX ON)
SET(ASSIMP_WARNINGS_AS_ERRORS ON)

# Disable all formats by default
SET(ASSIMP_BUILD_3DS_IMPORTER OFF)
SET(ASSIMP_BUILD_3D_IMPORTER OFF)
SET(ASSIMP_BUILD_3MF_IMPORTER OFF)
SET(ASSIMP_BUILD_AC_IMPORTER OFF)
SET(ASSIMP_BUILD_AMF_IMPORTER OFF)
SET(ASSIMP_BUILD_ASE_IMPORTER OFF)
SET(ASSIMP_BUILD_ASSBIN_IMPORTER OFF)
SET(ASSIMP_BUILD_B3D_IMPORTER OFF)
SET(ASSIMP_BUILD_BVH_IMPORTER OFF)
SET(ASSIMP_BUILD_COLLADA_IMPORTER OFF)
SET(ASSIMP_BUILD_CSM_IMPORTER OFF)
SET(ASSIMP_BUILD_DXF_IMPORTER OFF)
SET(ASSIMP_BUILD_FBX_IMPORTER OFF)
SET(ASSIMP_BUILD_GLTF_IMPORTER OFF)
SET(ASSIMP_BUILD_HMP_IMPORTER OFF)
SET(ASSIMP_BUILD_IFC_IMPORTER OFF)
SET(ASSIMP_BUILD_IRR_IMPORTER OFF)
SET(ASSIMP_BUILD_IRRMESH_IMPORTER OFF)
SET(ASSIMP_BUILD_LWO_IMPORTER OFF)
SET(ASSIMP_BUILD_LWS_IMPORTER OFF)
SET(ASSIMP_BUILD_M3D_IMPORTER OFF)
SET(ASSIMP_BUILD_MD2_IMPORTER OFF)
SET(ASSIMP_BUILD_MD3_IMPORTER OFF)
SET(ASSIMP_BUILD_MD5_IMPORTER OFF)
SET(ASSIMP_BUILD_MDC_IMPORTER OFF)
SET(ASSIMP_BUILD_MDL_IMPORTER OFF)
SET(ASSIMP_BUILD_MMD_IMPORTER OFF)
SET(ASSIMP_BUILD_MS3D_IMPORTER OFF)
SET(ASSIMP_BUILD_NDO_IMPORTER OFF)
SET(ASSIMP_BUILD_NFF_IMPORTER OFF)
SET(ASSIMP_BUILD_OBJ_IMPORTER OFF)
SET(ASSIMP_BUILD_OFF_IMPORTER OFF)
SET(ASSIMP_BUILD_OGRE_IMPORTER OFF)
SET(ASSIMP_BUILD_OPENGEX_IMPORTER OFF)
SET(ASSIMP_BUILD_PLY_IMPORTER OFF)
SET(ASSIMP_BUILD_Q3BSP_IMPORTER OFF)
SET(ASSIMP_BUILD_Q3D_IMPORTER OFF)
SET(ASSIMP_BUILD_RAW_IMPORTER OFF)
SET(ASSIMP_BUILD_SIB_IMPORTER OFF)
SET(ASSIMP_BUILD_SMD_IMPORTER OFF)
SET(ASSIMP_BUILD_STL_IMPORTER OFF)
SET(ASSIMP_BUILD_TERRAGEN_IMPORTER OFF)
SET(ASSIMP_BUILD_X_IMPORTER OFF)
SET(ASSIMP_BUILD_X3D_IMPORTER OFF)
SET(ASSIMP_BUILD_XGL_IMPORTER OFF)

# Enable only essential formats
SET(ASSIMP_BUILD_OBJ_IMPORTER ON) # Most common format
SET(ASSIMP_BUILD_FBX_IMPORTER ON) # Industry standard
SET(ASSIMP_BUILD_GLTF_IMPORTER ON) # Modern web format
SET(ASSIMP_BUILD_COLLADA_IMPORTER ON) # Common interchange format
SET(ASSIMP_BUILD_STL_IMPORTER ON) # 3D printing format

# Disable all exporters by default
SET(ASSIMP_BUILD_3DS_EXPORTER OFF)
SET(ASSIMP_BUILD_3MF_EXPORTER OFF)
SET(ASSIMP_BUILD_ASSBIN_EXPORTER OFF)
SET(ASSIMP_BUILD_ASSXML_EXPORTER OFF)
SET(ASSIMP_BUILD_COLLADA_EXPORTER OFF)
SET(ASSIMP_BUILD_FBX_EXPORTER OFF)
SET(ASSIMP_BUILD_GLTF_EXPORTER OFF)
SET(ASSIMP_BUILD_M3D_EXPORTER OFF)
SET(ASSIMP_BUILD_OBJ_EXPORTER OFF)
SET(ASSIMP_BUILD_OFF_EXPORTER OFF)
SET(ASSIMP_BUILD_OPENGEX_EXPORTER OFF)
SET(ASSIMP_BUILD_PLY_EXPORTER OFF)
SET(ASSIMP_BUILD_STL_EXPORTER OFF)
SET(ASSIMP_BUILD_X_EXPORTER OFF)
SET(ASSIMP_BUILD_X3D_EXPORTER OFF)

# Enable only essential exporters
SET(ASSIMP_BUILD_OBJ_EXPORTER ON) # Most common format
SET(ASSIMP_BUILD_GLTF_EXPORTER ON) # Modern web format
SET(ASSIMP_BUILD_FBX_EXPORTER ON) # Industry standard

# Disable unnecessary features
SET(ASSIMP_BUILD_ZLIB OFF) # Use system zlib
SET(ASSIMP_BUILD_DRACO OFF) # Disable Draco compression
SET(ASSIMP_BUILD_OPENDDL OFF) # Disable OpenDDL
SET(ASSIMP_BUILD_OPENDDL_PARSER OFF)
SET(ASSIMP_BUILD_OPENDDL_STATIC_LIBRARY OFF)
