# Protobuf

# Flags configuration:
SET(protobuf_BUILD_TESTS OFF)
SET(protobuf_WITH_ZLIB OFF)
SET(BUILD_SHARED_LIBS OFF)
SET(ABSL_RUN_TESTS OFF)
SET(BUILD_TESTING OFF)
SET(protobuf_ABSL_PROVIDER package)
SET(protobuf_BUILD_LIBUPB ON)
SET(protobuf_BUILD_CONFORMANCE OFF)
SET(protobuf_INSTALL OFF)
SET(protobuf_MSVC_STATIC_RUNTIME OFF)
SET(protobuf_BUILD_EXAMPLES OFF)
SET(protobuf_BUILD_PROTOBUF_BINARIES ON)
SET(protobuf_BUILD_SHARED_LIBS OFF)
SET(protobuf_BUILD_TESTS OFF)
SET(protobuf_BUILD_TOOLS OFF)
SET(protobuf_BUILD_UPB ON)

IF(FU_CONF_DEBUG)
  SET(CMAKE_MSVC_RUNTIME_LIBRARY ${FU_MSVC_RUNTIME_DEBUG})
ELSEIF(FU_CONF_RELEASE)
  SET(CMAKE_MSVC_RUNTIME_LIBRARY ${FU_MSVC_RUNTIME_RELEASE})
ENDIF()

# Paths:
SET(PROT_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/External/protobuf)
SET(absl_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../build/${FUEGO_PLATFORM}/Engine/External/abseil)

SET(PROTOC ${CMAKE_CURRENT_SOURCE_DIR}/../build/${FUEGO_PLATFORM}/output/$<CONFIG>/protoc)
SET(PROTO_IN ${CMAKE_CURRENT_SOURCE_DIR}/Fuego/ProtoIn)
SET(PROTO_OUT ${CMAKE_CURRENT_SOURCE_DIR}/Fuego/ProtoOut)

ADD_SUBDIRECTORY(${PROT_ROOT})

GET_DIRECTORY_PROPERTY(PROT_TARGETS DIRECTORY ${PROT_ROOT} BUILDSYSTEM_TARGETS)
FOREACH(target ${PROT_TARGETS})
  SET_TARGET_PROPERTIES(${target} PROPERTIES FOLDER "External/Protobuf")
ENDFOREACH()
SET_TARGET_PROPERTIES(
  utf8_range utf8_validity
  PROPERTIES FOLDER "External/Protobuf"
)

SET(SCENE_GENERATED_PROTO_SRCS
    "${PROTO_OUT}/SceneObjects.pb.cc"
    CACHE STRING "Generated Proto source file"
)
SET(SCENE_GENERATED_PROTO_HDRS
    "${PROTO_OUT}/SceneObjects.pb.h"
    CACHE STRING "Generated Proto source file"
)

ADD_CUSTOM_COMMAND(
  OUTPUT ${SCENE_GENERATED_PROTO_SRCS} ${SCENE_GENERATED_PROTO_HDRS}
  COMMAND ${PROTOC} --proto_path=${PROTO_IN} --cpp_out=${PROTO_OUT} SceneObjects.proto
  DEPENDS ${PROTO_IN}/SceneObjects.proto protobuf::protoc
  COMMENT "Generating Protocol Buffers sources"
  VERBATIM
)
ADD_CUSTOM_TARGET(ProtoGen DEPENDS ${SCENE_GENERATED_PROTO_SRCS} ${SCENE_GENERATED_PROTO_HDRS})
SET_TARGET_PROPERTIES(
  ProtoGen
  PROPERTIES FOLDER "Build/ProtoGen"
)
